default_install_hook_types: [pre-commit]
default_stages: [commit, push]
default_language_version:
  python: python3.10.13
ci:
  autofix_commit_msg: |
    ci(pre-commit): Autofixing commit msg from pre-commit.com hooks
  autofix_prs: true
  autoupdate_branch: ""
  autoupdate_commit_msg: "ci(autoupdate): Autoupdating commit msg"
  autoupdate_schedule: weekly
  skip: []
  submodules: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        exclude: k8s_deployment.example.yml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.10
        args:
          - --config=pyproject.toml

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.265'
    hooks:
      - id: ruff
        entry: bash -c 'ruff check "$@" || true' --
        args:
          - --config=pyproject.toml
        verbose: true
