"""db definition

Revision ID: 05c456d9a1db
Revises:
Create Date: 2023-09-27 14:25:02.937311

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "05c456d9a1db"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


POPULATE_ROLE_TABLE: str = """
    INSERT INTO roles(name)
    VALUES ('admin'),
           ('client');
"""

POPULATE_USER_TABLE: str = """
    INSERT INTO users(id,
                     name,
                     email,
                     hashed_password,
                     is_active,
                     is_logged_in,
                     role_id)
    VALUES (1,
            'admin',
            'admin@ibc.com',
            '$2b$12$zX6L9xYc82wiy5VxE8igT.isAdFbYs7zwXddSfk/uaxmk/ot.CWae',
            true,
            false,
            1),
            (6,
            'user',
            'user@ibc.com',
            '$2b$12$IJmtQ9Upo5c.EGE8t70wV.Bty4jpNoKjzRyIU81pgt23sQIm4KYT2',
            true,
            false,
            2);
"""


def populate_tables() -> None:
    op.execute(POPULATE_ROLE_TABLE)
    op.execute(POPULATE_USER_TABLE)


def clean_role() -> None:
    op.execute("DELETE FROM users;")
    op.execute("DELETE FROM roles;")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_logged_in", sa.Boolean(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    populate_tables()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("roles")
    # ### end Alembic commands ###
